spring.ai.mcp.client.sse.connections:
  person-mcp-server:
    url: http://localhost:8060
  account-mcp-server:
    url: http://localhost:8040


#spring:
#  ai:
#    openai:
#      api-key: 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      

